version: "3.9"

services:

  postgres:
    image: postgres:13.12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=job_service_jobstreet
    volumes:
      - job-service-prod-data-volume:/var/lib/postgresql/data
    networks:
      - job-network
    # ports:
    #   - 5432:5432
    user: postgres

  job_service:
    container_name: backend-jobstreet-job-service-prod-container
    image: thanhquy1105/backend-jobstreet-job-service-prod
    build:
      context: .
      target: production
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - DB_SOURCE=postgresql://admin:admin@postgres:5432/job_service_jobstreet?sslmode=disable
    ports:
      - 8080:8080
      - 9090:9090
    depends_on:
      - postgres
    networks:
      - job-network
    restart: on-failure
    command: [ "/app/main" ]

networks:
  job-network:

volumes:
  job-service-prod-data-volume:

