mutation UpdateJob($id: ID!, $input: UpdateJobListingInput!){
  updateJobListing(id: $id, input: $input){
    _id
    title
    description
    company
    url
  }
}

{
  "id": "1",
  "input": {
    "title": "Software Development Enginee "
  }
}