// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	Status      string `json:"status"`
}

type DeleteJobResponse struct {
	DeletedJobID string `json:"deletedJobId"`
}

type JobListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	Status      string `json:"status"`
}

type Mutation struct {
}

type Query struct {
}

type SavedJob struct {
	ID          string `json:"_id"`
	JobID       string `json:"jobID"`
	CandidateID string `json:"candidateID"`
}

type UpdateJobListingInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
}
