apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobstreet-job-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-job-service-app
  template:
    metadata:
      labels:
        app: my-job-service-app
    spec:
      containers:
        - name: my-container
          image: us-central1-docker.pkg.dev/jobstreet-421314/jobstreet-job-repo/job-serivce-image
          ports:
            - containerPort: 8080
            - containerPort: 9090

apiVersion: v1
kind: Service
metadata:
  name: my-job-service
spec:
  selector:
    app: my-job-service-app
  ports:
    - port: 8080
      protocol: TCP
      name: gateway  
      targetPort: 8080
    - port: 9090
      protocol: TCP 
      name: grpc
      targetPort: 9090
  type: LoadBalancer