// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: rpc_close_job.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CloseJobRequest) Reset() {
	*x = CloseJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_close_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseJobRequest) ProtoMessage() {}

func (x *CloseJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_close_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseJobRequest.ProtoReflect.Descriptor instead.
func (*CloseJobRequest) Descriptor() ([]byte, []int) {
	return file_rpc_close_job_proto_rawDescGZIP(), []int{0}
}

func (x *CloseJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CloseJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CloseJobResponse) Reset() {
	*x = CloseJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_close_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseJobResponse) ProtoMessage() {}

func (x *CloseJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_close_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseJobResponse.ProtoReflect.Descriptor instead.
func (*CloseJobResponse) Descriptor() ([]byte, []int) {
	return file_rpc_close_job_proto_rawDescGZIP(), []int{1}
}

func (x *CloseJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rpc_close_job_proto protoreflect.FileDescriptor

var file_rpc_close_job_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6a, 0x6f, 0x62, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74,
	0x2e, 0x6a, 0x6f, 0x62, 0x22, 0x21, 0x0a, 0x0f, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x10, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x53, 0x45, 0x43, 0x2d, 0x4a, 0x6f, 0x62, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x6a, 0x6f, 0x62, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_close_job_proto_rawDescOnce sync.Once
	file_rpc_close_job_proto_rawDescData = file_rpc_close_job_proto_rawDesc
)

func file_rpc_close_job_proto_rawDescGZIP() []byte {
	file_rpc_close_job_proto_rawDescOnce.Do(func() {
		file_rpc_close_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_close_job_proto_rawDescData)
	})
	return file_rpc_close_job_proto_rawDescData
}

var file_rpc_close_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_close_job_proto_goTypes = []interface{}{
	(*CloseJobRequest)(nil),  // 0: jobstreet.job.CloseJobRequest
	(*CloseJobResponse)(nil), // 1: jobstreet.job.CloseJobResponse
}
var file_rpc_close_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_close_job_proto_init() }
func file_rpc_close_job_proto_init() {
	if File_rpc_close_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_close_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_close_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_close_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_close_job_proto_goTypes,
		DependencyIndexes: file_rpc_close_job_proto_depIdxs,
		MessageInfos:      file_rpc_close_job_proto_msgTypes,
	}.Build()
	File_rpc_close_job_proto = out.File
	file_rpc_close_job_proto_rawDesc = nil
	file_rpc_close_job_proto_goTypes = nil
	file_rpc_close_job_proto_depIdxs = nil
}
